### ISSUE TITLE
JSON file can't contain comments.

### ISSUE THREAD

**Issue by mc-zone** [mattn/webapi-vim#22]
Hi!
l using webapi-vim to include a json file and work for emmet-vim. 
When I writing some comments in this file, Some error has occurred, and can't be work.
Both `//comments` and `/*comments*/`.
This means that I can't put comments in json files?

**Comment by mattn** [comment]
See the spec of JSON.

On 1/25/15, Ma Cheng <notifications@github.com> wrote:
> Hi!
> l using webapi-vim to include a json file and work for emmet-vim.
> When I writing some comments in this file, Some error has occurred, and
> can't be work.
> Both `//comments` and `/*comments*/`.
> This means that I can't put comments in json files?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/webapi-vim/issues/22


-- 
- Yasuhiro Matsumoto

**Comment by mc-zone** [comment]
Sorry. It was my fault. I mistook the `Emmet.sublime-settings` file for this.
