### ISSUE TITLE
Error detected while processing function webapi#json#decode

### ISSUE THREAD

**Issue by programes** [mattn/webapi-vim#26]
Error detected while processing function webapi#json#decode:
line 33:
E15: Invalid expression:
E15: Invalid expression:
Press ENTER or type command to continue

**Comment by programes** [comment]
Error detected while processing function webapi#json#decode:
line   33:
E15: Invalid expression: 
E15: Invalid expression: 
Press ENTER or type command to continue

**Comment by programes** [comment]
I use emmet.vim with web-api

**Comment by mattn** [comment]
What json did you decode?

**Comment by mattn** [comment]
timed-out
