### ISSUE TITLE
SHA1 doesn't work properly.

### ISSUE THREAD

**Issue by fx-kirin** [mattn/webapi-vim#28]
Thanks for the great plugin. I'd like to report a bug related SHA1.

```
:echo webapi#base64#b64encodebin(webapi#sha1#sha1('test'))
```
returns
```
+jzkkbYx+g8RDpvBf9JnybGNt0E=
```
It should be 
```
qUqP5cyxm6YcTAhz05Hph5gvu9M=
```
as I got same result of sha1 test with python and ruby.

Environment
- `commit 204dc995d8934a9701b9abebcb3049a2fdba0cfb`.
- Ubuntu 16.04
- Vim 8.0.22
I was trying to use `hateblo.vim` but it doesn't work because of this problem.

**Comment by mattn** [comment]
Should be fixed in recent commits. This bug was depend on size-of number type.
